=== aion-kelvin/AionRpc/json-schema/v3/eth_getBlockByNumber.response.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",

    "title": "eth_getBlockByNumber response",
    "description": "Returns information about a block by block number.",

    "type": "object",
    "additionalProperties": false,
    "required": [
        "number", "hash", "parentHash", "nonce", "logsBloom", "transactionsRoot", "stateRoot", "receiptsRoot", "miner", "difficulty", "totalDifficulty", "extraData", "size", "nrgLimit", "nrgUsed", "gasLimit", "gasUsed", "timestamp", "transactions", "solution" 
    ],
    "properties": {
        "number": {
            "$ref": "type.json#/definitions/QUANTITY",
            "description": "the block number. null when it is pending block."
        },
        "hash": {
            "$ref": "type.json#/definitions/DATA32",
            "description": "hash of the block. null when it is pending block."
        },
        "parentHash": {
            "$ref": "type.json#/definitions/DATA32",
            "description": "hash of the parent block."
        },
        "nonce": {
            "$ref": "type.json#/definitions/DATA32",
            "description": "nonce of the generated proof-of-work. null when it is pending block."
        },
        "logsBloom": {
            "$ref": "type.json#/definitions/DATA256",
            "description": "the bloom filter for the logs of the block. null when it is pending block."
        },
        "transactionsRoot": {
            "$ref": "type.json#/definitions/DATA32",
            "description": "the root of the transaction trie of the block."
        },
        "stateRoot": {
            "$ref": "type.json#/definitions/DATA32",
            "description": "the root of the final state trie of the block."
        },
        "receiptsRoot": {
            "$ref": "type.json#/definitions/DATA32",
            "description": "the root of the receipts trie of the block."
        },
        "miner": {
            "$ref": "type.json#/definitions/DATA32",
            "description": "the address of the beneficiary to whom the mining rewards were given."
        },
        "difficulty": {
            "$ref": "type.json#/definitions/QUANTITY",
            "description": "integer of the difficulty for this block."
        },
        "totalDifficulty": {
            "$ref": "type.json#/definitions/QUANTITY",
            "description": "integer of the total difficulty of the chain until this block."
        },
        "extraData": {
            "$ref": "type.json#/definitions/DATA",
            "description": "the \"extra data\" field of this block."
        },
        "size": {
            "$ref": "type.json#/definitions/QUANTITY",
            "description": "integer the size of this block in bytes."
        },
        "nrgLimit": {
            "$ref": "type.json#/definitions/QUANTITY",
            "description": "the maximum energy allowed in this block in nAmps."
        },
        "nrgUsed": {
            "$ref": "type.json#/definitions/QUANTITY",
            "description": "the total used energy by all transactions in this block in nAmps."
        },
        "gasLimit": {
            "$ref": "type.json#/definitions/QUANTITY",
            "description": "same as nrgLimit; duplicated for Ethereum-compatibility purposes."
        },
        "gasUsed": {
            "$ref": "type.json#/definitions/QUANTITY",
            "description": "same as nrgUsed; duplicated for Ethereum-compatibility purposes."
        },
        "timestamp": {
            "$ref": "type.json#/definitions/QUANTITY",
            "description": "the unix timestamp for when the block was collated, in seconds."
        },
        "transactions": {
            "type": "array",
            "description": "Array of transaction objects, or 32 Bytes transaction hashes depending on the last given parameter."
        },
        "solution": {
            "$ref": "type.json#/definitions/DATA",
            "description": "solution for the generated proof-of-work."
        }
    }
}

=== aion-kelvin/AionRpc/json-schema/v3/ex.resp.json
{
        "number": "0x28cce9",
        "hash": "0x8f8b3dd16c6c972d0910af4c50e13b4521966ff6d9909922bc1e366461b4fe52",
        "parentHash": "0xc1e7987aedf107c81b663ce7d092251dddca6c5e2c37e07e2d937b7db0cc6108",
        "nonce": "0x000000000000000000000000c001b43b00000000000000006437700000000000",
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000001000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000440000000000000000000000000000000000000000000000000000000000000001000000000000000",
        "transactionsRoot": "0xcf105253fc2f325a908abd66cfb200f3dfb58f401c58751e64186af97d5202ac",
        "stateRoot": "0x1dd00fa0fd6b1635e54dbee33d5ce19454bfb948d5027f5a989dfb4cd46fee99",
        "receiptsRoot": "0x9417d2515d3656d3aaf316506bf8afcb740759de5d23cd6538ba8269486d88aa",
        "miner": "0xa0f9f5d4925501974403b34226bbf01eceba58582719c5744f86880959c052d2",
        "difficulty": "0x8a4214",
        "totalDifficulty": "0x1d598faf9420",
        "extraData": "0x4c55584f52000000000000000000000000000000000000000000000000000000",
        "size": "0x84a",
        "nrgLimit": "0xe4b058",
        "nrgUsed": "0x7c1e",
        "gasLimit": "0xe4b058",
        "gasUsed": "0x7c1e",
        "timestamp": "0x5c8c04f9",
        "transactions": [
          {
            "nrgPrice": "0x4a817c800",
            "nrg": "0x7c1e",
            "transactionIndex": "0x0",
            "nonce": "0xebb",
            "input": "0x4178462f00000000000000000000000000000021",
            "blockNumber": "0x28cce9",
            "gas": "0x7c1e",
            "from": "0xa0cfe4620faef3d35f8a842e361d228520f1697eec05b643b34293b88cca2aec",
            "to": "0xa03c3dc1f9c3cc2a02155fde9ad33f80e2d0a3ea6216aba5b2d11962d25f27bf",
            "value": "0x",
            "hash": "0x8571465914fca68c39dfd127a3a429856fccc9e121ccfc276ced4f95f3331831",
            "gasPrice": "0x4a817c800",
            "timestamp": "0x5c8c04f9"
          }
        ],
        "solution": "0x001f405900422b9b27c9dc209d2cb1dd9a14c9ffb333179aa86d65c24056bb096334fb05086ac818f36e40fd00419a8a76c6ff81fb567801d678796f8ad30bfc20da346a6d433164c423ea8a1c4960017c22474fa169cb51059745e60f3c4299bfdfea5685215eab5b06a67b92b922846ef18906b940fae59e38ba321f11a7ffdda69e5c06234afa96fa348d39169b4a34c152f7e94f25f51e7d3b19efdc753a28e437e589741b5726daa935ae36da7203bb91e2d5410ad4aa201d757b369d0357a4abffce7a0c1fd3819c73f427e95810751ebf6cc5f829ad6e0531042224d52e3bd9983869af5aaf27daf2381146e487aa22807fe3aa236d9c5519cc48d1e221d1add527fd4c440bfa4d8fb6f5b79bf7dfc61814efd46623159371297212ac50826d15f1596d145f465c7b065974caa55f48ad10ef56ec470607bba056d5268b9282f32512d53c46622c26329b161891b06d07a74308de6c5ed7a0cfbab13e03277928d7980c3ca2bef7099e7956d824581eb8bff09c1ae370dfeb1d407096fea5953a9d51df9ce47fff2e0d9c2320bf34bbe227e0e5738ee6375c995ee03aaaf50dace95bf4446754a0d75e12984e70b424366b9f4b9305cb1aedd2b832aba89b4830664bc3f0a314b4a9b6591e63c1f1067661dedb65004f4e337e9a16c7412d53ff0e129fff7263095c39b24917fb5968c56748556ef631267ca9b87205e6be3fa1c88ccbf3cc015a32a2b5b5b70bed7cb9df70ca96b7846e1d4f232ece14ba34b4c8723aba5a2408ea005037583175c83a3dca197e30b616fd109043460935427d747ddc3789f66d6788e0b8ffaa7747cc996b49bb398870fe4d758b538ced98cb40f7b5a90d5bcf6516a52f64aaf6ea2722c0e7d4aaf58df3080617daa8baaf3515dcbb6e555b36b76740964dde636ce4163ea1fdae5eb0147d1e893988a5ac465d7819f9904e2bc9b2e0231a105ef33e4349d2aee16324aa7117549d00c1df49a98131ef1847fe043347b55164df43dea3ef03fce829dde12da4b469151aac0a1aa76a5daab5780203fe4b4266389ab16a7e73c513ff53413df263fc423a070e169dbfd4b21cdb216e1e1aea2a47721d8148d0ef058089604d6b26f77e10ac0d61ee7e4abcab6332c00508104ffdb2b4a31bb8053a0ed77174a9c9366be9c89b10f7a9441fb3ab2c148b0032d40a45d0565869edfe4f143da2751e8423d26c65a546903e1e36aa5cc2f03df6027eaac344d13a836c0311032ba31c95758644b8546603ba8e49c0c04f61cd6afa11ce69d0bc57861aaca6b303a021944437a5e46d770f1537f9dee31c4c4a367d9253cf6e61b4d5e802df84ef79de8f9dd779eb50efa04e080650af8b2476cd2af0aa2b2ba8c8e7d6d623a134d230e064e3d20cb41bfdfe44892a8ec222ddb02a7d4f940dbaac396df7e3d8b9b6b3319977bb5e08c93ce97263146d80b765558564ed7a8b296316ce895460b96b069d02ea4c82f3d4ded8566c205cf1c2f0ea39bf42e819b12b309185fc2942a132fd7183e6524b1c5d1718fa5dba23c8f39377863a8ce1fe815e597de2f6bc24a2b42e5a3bc2cfacf29b05fab4a27a7233aea1de07c64da1b4c704cbcf09797cd60c7681c6126bb520fea160d756aeef08916b8ea694bc2831ebf90e1767bbc52ada9b7517fb08ca384c841159386fcfbc3b668be2b6c555ec6ec1da17fdd0f987d2b7d2de4587465fcd94607655f9e9060406c873fe96a5d3d32fecd57c5486eecf0d8c737fc4e0293a52db03689fe87ea1fd304e2dd5be061be7e2d47508b184585a9545b37130161526d5e9374af7202cef3d1fd770a8b33701ff9dcbb0484cf974cb4923453fc5770ae46ed2b8c3bf98e6c0de3b587fda65f43d20789df23f24ed7108a522e0deccaa472fde84aaf878c8760e5e102f1c86baa5f4467100a11bb39b981522d2b179f6d331eb092a782ce916f62f9c32e8fb7fc077eaf73ac48c"
      }
